//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VKLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка на добавление в друзья от данного пользователя одобрена.
        /// </summary>
        internal static string AddFriendStatus_Accepted {
            get {
                return ResourceManager.GetString("AddFriendStatus_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторная отправка заявки.
        /// </summary>
        internal static string AddFriendStatus_Resubmit {
            get {
                return ResourceManager.GetString("AddFriendStatus_Resubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка на добавление данного пользователя в друзья отправлена.
        /// </summary>
        internal static string AddFriendStatus_Sended {
            get {
                return ResourceManager.GetString("AddFriendStatus_Sended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус ответа неизвестен.
        /// </summary>
        internal static string AddFriendStatus_Unknown {
            get {
                return ResourceManager.GetString("AddFriendStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помолвлен.
        /// </summary>
        internal static string MaritalStatus_Engaged {
            get {
                return ResourceManager.GetString("MaritalStatus_Engaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Влюблён.
        /// </summary>
        internal static string MaritalStatus_InLove {
            get {
                return ResourceManager.GetString("MaritalStatus_InLove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всё сложно.
        /// </summary>
        internal static string MaritalStatus_ItsComplicated {
            get {
                return ResourceManager.GetString("MaritalStatus_ItsComplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женат.
        /// </summary>
        internal static string MaritalStatus_Married {
            get {
                return ResourceManager.GetString("MaritalStatus_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Встречается.
        /// </summary>
        internal static string MaritalStatus_Meets {
            get {
                return ResourceManager.GetString("MaritalStatus_Meets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не женат.
        /// </summary>
        internal static string MaritalStatus_SinglMaritalStatus_Single {
            get {
                return ResourceManager.GetString("MaritalStatus_SinglMaritalStatus_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В активном поиске.
        /// </summary>
        internal static string MaritalStatus_TheActiveSearch {
            get {
                return ResourceManager.GetString("MaritalStatus_TheActiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Женский.
        /// </summary>
        internal static string Sex_Female {
            get {
                return ResourceManager.GetString("Sex_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской.
        /// </summary>
        internal static string Sex_Male {
            get {
                return ResourceManager.GetString("Sex_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан.
        /// </summary>
        internal static string Sex_Unknown {
            get {
                return ResourceManager.GetString("Sex_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По популярности.
        /// </summary>
        internal static string UserSort_ByPopularity {
            get {
                return ResourceManager.GetString("UserSort_ByPopularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По дате регистрации.
        /// </summary>
        internal static string UserSort_ByRegDate {
            get {
                return ResourceManager.GetString("UserSort_ByRegDate", resourceCulture);
            }
        }
    }
}
